drop table if exists book cascade;
create table book (
    cost integer,
    id bigint generated by default as identity,
    category varchar(255) not null check (category in ('DEVELOP','CULTURE','MONEY')),
    name varchar(255) not null unique,
    primary key (id)
)

